#!/usr/bin/env bash

# Accepts a version string and prints it incremented by one.
# Usage: increment_version <version> [<position>] [<leftmost>]
increment_version() {
  declare -a part=(${1//\./ })
  declare new
  declare -i carry=1

  for ((CNTR = ${#part[@]} - 1; CNTR >= 0; CNTR -= 1)); do
    len=${#part[CNTR]}
    new=$((part[CNTR] + carry))
    [ ${#new} -gt $len ] && carry=1 || carry=0
    [ $CNTR -gt 0 ] && part[CNTR]=${new: -len} || part[CNTR]=${new}
  done

  new="${part[*]}"
  if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo -e "${new// /.}"
  elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "${new// /.}"
  elif [[ "$OSTYPE" == "cygwin" ]]; then
    echo "not correct system - cygwin detected"
    exit
  fi
}
clean_publish_pypi() {
  VERSION=$(cat version)
  increment_version $VERSION >version
  VERSION=$(cat version)

  sudo rm -rf dist
  rm -rf html
  rm -rf doc
  # python3.9 -m pdoc ./tronpytool
  mv html/tronpytool docs/tronpytool
  rm html

  python3.9 -m pip install --user --upgrade setuptools wheel
  # python3 -m pip install --upgrade setuptools wheel

  sudo python3.9 setup.py clean sdist bdist_wheel
  python3.9 -m twine upload dist/* --verbose

  echo "please update the package by using this command"
  echo "pip3 install tronpytool==$VERSION"
  echo "pi tronpytool==$VERSION"
  echo "pc tronpytool==$VERSION"
  echo "sudo pip3 install tronpytool==$VERSION --upgrade"
  echo "wait 30 seconds until it gets uploaded online..."
  # echo "ready and install it again.."
  # sudo pip3 install --proxy 127.0.0.1:1087 tronpytool==$VERSION
}
git_update() {
  local gitcheck=$(git diff --shortstat)
  git add .
  echo "Please enter your commit message:"
  # shellcheck disable=SC2162
  read name
  git commit -m "♻️ $name $gitcheck"
  git push origin
  git push github

  echo "♻️ You can open ${GIT_LOC} or git clone ${GIT_LOC}.git to copy to the local"
}
swap_src() {
  local DEV_SRC=$HOME/Documents/b95/devtron/tronpytool
  local DEPLOY_SRC=$HOME/Documents/piplines/tron-tool-py/tronpytool
  if [[ -d "$DEV_SRC" ]]; then
    echo "now swapping the source code"
    rm -rf tronpytool
    cp -R $DEV_SRC $DEPLOY_SRC
  fi
}

swap_src
clean_publish_pypi
git_update
